import Head from 'next/head'
import { HomeView } from './HomeView'
import { useSelector } from 'react-redux'
import { quoteManagementSelector } from '../app/domain/quoteManagement/selector/QuoteManagementSelector'

const Index = () => {

    const quotes = useSelector(quoteManagementSelector.quotes)

    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name='description' content='Generated by create next app'/>
                <link rel='icon' href='/public/favicon.ico'/>
            </Head>
            <HomeView quotes={quotes}/>
        </>
    )
}

export default Index
