import Head from 'next/head'
import {HomeView} from './HomeView'

const Index = () => {
    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name='description' content='Generated by create next app'/>
                <link rel='icon' href='/public/favicon.ico'/>
            </Head>
            <HomeView/>
        </>
    )
}

export default Index
